<a href="https://colab.research.google.com/github/DehitTrivedi/DataScienceBootcampFall2023/blob/main/Week3_practiceQustions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1

In [3]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 3, 6])

# Stack A and B vertically
stacked_vertically = np.vstack((A, B))

# Stack A and B horizontally
stacked_horizontally = np.hstack((A, B))

print("Stacked Vertically:")
print(stacked_vertically)

print("Stacked Horizontally:")
print(stacked_horizontally)


Stacked Vertically:
[[1 2 3]
 [4 3 6]]
Stacked Horizontally:
[1 2 3 4 3 6]


# Question 2

In [4]:
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

Common Elements: [3]


# Question 3

In [5]:
A = np.array([2, 6, 8, 12, 4, 7, 11, 5, 9])
range_mask = (A >= 5) & (A <= 10)
result = A[range_mask]
print("Numbers within the range [5, 10]:", result)


Numbers within the range [5, 10]: [6 8 7 5 9]


# Question 4

In [6]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Rows:")
print(filtered_rows)


Filtered Rows:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


# Question 5

In [7]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_data = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_data)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


#Question 6

In [8]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)


#Question 7


In [9]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

row_sum_greater_than_100 = df[df.sum(axis=1) > 100]
print("Rows with sum > 100:")
print(row_sum_greater_than_100)


Rows with sum > 100:
     0   1   2   3
1   29  32  38  19
3   21  37  35  25
6   28  13  36  31
7   33  23  36  29
8   36  26  27  14
11  31  14  35  37
13  19  32  32  18
